name: TwoPlayerHorseRiding
author: Kovalski
version: 0.1

#It feed the horse automatically with the hay bale in the rider's hotbar slot.
auto_horse_feed: true

#Health values from auto feed
hay_bale: 20.0

#Mobs you can enable to two player ride
HORSE: true
DONKEY: true
MULE: true
LLAMA: true